// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecKaliteDb.Models;

#nullable disable

namespace SecKaliteDb.Migrations
{
    [DbContext(typeof(SecKaliteDbDbContext))]
    [Migration("20240805073323_LoginTableEklendi")]
    partial class LoginTableEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecKaliteDb.Models.BedenNumara", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Beden")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BedenNumara");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Birim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BirimAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Birim");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Iade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EnvanterDurumu")
                        .HasColumnType("int");

                    b.Property<DateTime>("IadeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("PersonelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("Iade");
                });

            modelBuilder.Entity("SecKaliteDb.Models.KkdEnvanterTakip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BedenNumaraId")
                        .HasColumnType("bigint");

                    b.Property<long>("BirimId")
                        .HasColumnType("bigint");

                    b.Property<long?>("DegistirenId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("DegistirmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("KkdGrubuId")
                        .HasColumnType("bigint");

                    b.Property<long?>("KkdNiteligiId")
                        .HasColumnType("bigint");

                    b.Property<long?>("OlusturanId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("PersonelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BedenNumaraId");

                    b.HasIndex("BirimId");

                    b.HasIndex("KkdGrubuId");

                    b.HasIndex("KkdNiteligiId");

                    b.HasIndex("PersonelId");

                    b.ToTable("KkdEnvanterTakip");
                });

            modelBuilder.Entity("SecKaliteDb.Models.KkdGrubu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("KkdGrubuAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("KkdGrubu");
                });

            modelBuilder.Entity("SecKaliteDb.Models.KkdNiteligi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("KkdGrubuId")
                        .HasColumnType("bigint");

                    b.Property<string>("KkdNiteligiAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("KkdGrubuId");

                    b.ToTable("KkdNiteligi");
                });

            modelBuilder.Entity("SecKaliteDb.Models.LoginRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginRequest");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Personel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("KkdEnvanterTakipId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PersonelBirimId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UnvanId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PersonelBirimId");

                    b.HasIndex("UnvanId");

                    b.ToTable("Personel");
                });

            modelBuilder.Entity("SecKaliteDb.Models.PersonelBirim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BirimAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("PersonelBirim");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Teslimat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("EnvanterDurumu")
                        .HasColumnType("int");

                    b.Property<long>("PersonelId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PersonelId");

                    b.ToTable("Teslimat");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Unvan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Silindi")
                        .HasColumnType("bit");

                    b.Property<string>("UnvanAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unvan");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Iade", b =>
                {
                    b.HasOne("SecKaliteDb.Models.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SecKaliteDb.Models.KkdEnvanterTakip", b =>
                {
                    b.HasOne("SecKaliteDb.Models.BedenNumara", "BedenNumara")
                        .WithMany()
                        .HasForeignKey("BedenNumaraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecKaliteDb.Models.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecKaliteDb.Models.KkdGrubu", "KkdGrubu")
                        .WithMany()
                        .HasForeignKey("KkdGrubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecKaliteDb.Models.KkdNiteligi", "KkdNiteligi")
                        .WithMany()
                        .HasForeignKey("KkdNiteligiId");

                    b.HasOne("SecKaliteDb.Models.Personel", "Personel")
                        .WithMany("KkdEnvanterTakip")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BedenNumara");

                    b.Navigation("Birim");

                    b.Navigation("KkdGrubu");

                    b.Navigation("KkdNiteligi");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SecKaliteDb.Models.KkdNiteligi", b =>
                {
                    b.HasOne("SecKaliteDb.Models.KkdGrubu", "KkdGrubu")
                        .WithMany()
                        .HasForeignKey("KkdGrubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KkdGrubu");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Personel", b =>
                {
                    b.HasOne("SecKaliteDb.Models.PersonelBirim", "PersonelBirim")
                        .WithMany()
                        .HasForeignKey("PersonelBirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecKaliteDb.Models.Unvan", "Unvan")
                        .WithMany()
                        .HasForeignKey("UnvanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonelBirim");

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Teslimat", b =>
                {
                    b.HasOne("SecKaliteDb.Models.Personel", "Personel")
                        .WithMany("Teslimat")
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("SecKaliteDb.Models.Personel", b =>
                {
                    b.Navigation("KkdEnvanterTakip");

                    b.Navigation("Teslimat");
                });
#pragma warning restore 612, 618
        }
    }
}
